# -*- coding: utf-8 -*-
"""Python & Machine Learning Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/154vjFuIDwSfJ4I92X0d1Qp2tjc-yH77x
"""

OBJECTIVE:
Introduction to Python and its basic code, syntax for machine learning, supervised learning and unsupervised learning.

Python:
It is a widely used general-purpose, high level programming language. 
It was created by Guido van Rossum in 1991 and further developed by the Python Software Foundation. 
It was designed with an emphasis on code readability, and its syntax allows programmers to express their concepts in fewer lines of code.

Versions:
There are two major python version: Python 2 and Python 3.
Both are quite different from each other.

Variables:
In other programming languages like C, C++, and Java, you will need to declare the type of variables but in Python we don’t need to do that. 
We can just type in the variable and when values will be given to it, then it will automatically know whether the value given would be an int, float, or char or even a String.

# Python program to declare variables
firstNumber = 10
print(firstNumber)

secondNumber = 10.6
print(secondNumber)

firstNumber ="Hello World"
print(firstNumber)

Data Structures:
Python has mainly 4 built-in type data structures.
They are List, Dictionary, Tuple and Set.

List:
List is the most basic Data Structure in python. 
List is a mutable data structure i.e items can be added to list later after the list creation. 
append() function is used to add data to the list.

# Python program to illustrate a list 
  
# creates a empty list
numbers = [] 
  
# appending data in list
numbers.append(30)
numbers.append(35.5)
numbers.append("String")
  
print(numbers)

Input and Output:
Here, we will see how to take input from the user and hence manipulate it or simply display it. 
input() function is used to take input from the user.

# Python program to illustrate getting input from user
name = input("Enter your name: ") 
  
# user entered the name 'Agyeya'
print("Hello", name)

# Python program to get input from user
  
# accepting integer from the user
# the return type of input() function is string ,
# so we need to convert the input to integer
number1 = int(input("Enter first number : "))
number2 = int(input("Enter second number : "))
  
number3 = number1 * number2
print("Product is : ", number3)

Dictionary:
Dictionary in Python is an ordered collection of data values, used to store data values like a map, which, unlike other Data Types that hold only a single value as an element, Dictionary holds key:value pair. 
Key-value is provided in the dictionary to make it more optimized.

# Creating a Dictionary
# with Integer Keys
Dict = {1: 'A', 2: 'B', 3: 'C'}
print("\nDictionary with the use of Integer Keys: ")
print(Dict)
 
# Creating a Dictionary
# with Mixed keys
Dict = {'Name': 'Agyeya', 1: [1, 2, 3, 4]}
print("\nDictionary with the use of Mixed Keys: ")
print(Dict)

Tuple:
A Tuple is a collection of Python objects separated by commas. 
In someways a tuple is similar to a list in terms of indexing, nested objects and repetition but a tuple is immutable unlike lists which are mutable.

# Creating non-empty tuples
  
# One way of creation
tup = 'python', 'Agyeya'
print(tup)

Set:
A Set is an unordered collection data type that is iterable, mutable and has no duplicate elements.

# Python program to demonstrate sets
  
# Same as {"a", "b", "c"}
myset = set(["a", "b", "c"])
print(myset)
  
# Adding element to the set
myset.add("d")
print(myset)

Selection:
Selection in Python is made using the two keywords ‘if’ and ‘elif’ and else (elseif)

# Python program to illustrate selection statement
  
number1 = 34

if(number1>12):
    print("Entered number is greater than 12")

elif(number1<=12 and number1>=5):
    print("Entered number is less than or equal to 12 but greater than or equal to 5")
else:
    print("Number is less than 5")

Functions:
Functions are like a bunch of code that are intended to do a particular task in the whole Python script. 
Python used the keyword ‘def’ to define a function

Syntax:
def function-name(arguments):
            #function body

# Python program to illustrate functions
def hello():
    print("Hello")
    print("Hello again")
  
# calling function
hello()

# Python program to illustrate function with main

def getInteger():
    result = int(input("Enter integer : "))
    return result
  
def Main():
    print("Started")
  
    # calling the getInteger function and 
    # storing its returned value in the output variable
    output = getInteger()     
    print("Interger = " + str(output))
  
# now we are required to tell Python 
# for 'Main' function existence
if __name__=="__main__":
    Main()

Iteration (Looping):
These are used to iterate over a sequence (that is either a list, a tuple, a dictionary, a set, or a string) repeatedly. 
We will use for loop to demonstrate here.

# Python program to illustrate
# a simple for loop
  
for step in range(5):    
    print(step, end = " ")

Module:
A module is a file containing Python definitions and statements. 
A module can define functions, classes, and variables. 
A module can also include runnable code. Grouping related code into a module makes the code easier to understand and use. 
It also makes the code logically organized.
‘import’ keyword is used to import a particular module into your python code.

# Python program to illustrate
# math module
import math
  
def Main():
    number = -85
  
    # fabs is used to get the absolute value of a decimal
    number = math.fabs(number) 
    print(number)
      
      
if __name__=="__main__":
    Main()

Machine Learning:
Machine Learning is the field of study that gives computers the capability to learn without being explicitly programmed.

Types of Machine Learning Problems:
1. On basis of the nature of the learning “signal” or “feedback” available to a learning system

Supervised learning: 
The computer is presented with example inputs and their desired outputs, given by a “teacher”, and the goal is to learn a general rule that maps inputs to outputs. 
The training process continues until the model achieves the desired level of accuracy on the training data. Some real-life examples are:

- Image Classification: You train with images/labels. Then in the future you give a new image expecting that the computer will recognize the new object.
- Market Prediction/Regression: You train the computer with historical market data and ask the computer to predict the new price in the future.

Unsupervised learning: 
No labels are given to the learning algorithm, leaving it on its own to find structure in its input. 
It is used for clustering population in different groups. Unsupervised learning can be a goal in itself (discovering hidden patterns in data).

Clustering: 
You ask the computer to separate similar data into clusters, this is essential in research and science.

High Dimension Visualization: 
Use the computer to help us visualize high dimension data.

Generative Models: 
After a model captures the probability distribution of your input data, it will be able to generate more data. 
This can be very useful to make your classifier more robust.

2. On the basis of “output” desired from a machine learned system

Classification: 
Inputs are divided into two or more classes, and the learner must produce a model that assigns unseen inputs to one or more (multi-label classification) of these classes. 
This is typically tackled in a supervised way. 
Spam filtering is an example of classification, where the inputs are email (or other) messages and the classes are “spam” and “not spam”.

Regression: 
It is also a supervised learning problem, but the outputs are continuous rather than discrete. For example, predicting the stock prices using historical data.

Clustering: 
Here, a set of inputs is to be divided into groups. Unlike in classification, the groups are not known beforehand, making this typically an unsupervised task.

Density estimation: The task is to find the distribution of inputs in some space.

Dimensionality reduction: 
It simplifies inputs by mapping them into a lower-dimensional space. 
Topic modeling is a related problem, where a program is given a list of human language documents and is tasked to find out which documents cover similar topics.

Python libraries that used in Machine Learning are: 
 
Numpy
Scipy
Scikit-learn
Theano
TensorFlow
Keras
PyTorch
Pandas
Matplotlib
